### ISSUE TITLE
Suggestion: Include Example Outputs

### ISSUE THREAD

**Issue by terrabitz** [princjef/gomarkdoc#26]
# The Problem

When generating example documentation, all the example code is present and nicely formatted. However, it lacks the actual output of the Example function. For example, given the following `myfoo.go`:

```go
package myfoo

import "fmt"

func Hello(s string) string {
	return fmt.Sprintf("Hello %s!", s)
}
```

and its test file `myfoo_test.go`:

```go
package myfoo


func ExampleHello() {
	s := Hello("Bob")
	fmt.Println(s)
	// Output: Hello Bob!
}
```

I get the following for my generated markdown:

````markdown
...

<details><summary>Example</summary>
<p>

```go
{
	s := Hello("Bob")
	fmt.Println(s)

}
```

</p>
</details>

...
````

This generated example doesn't include my expected output of `Hello Bob!`, which could be useful for a reader.

# Recommendation

In the generated example details, an additional code block could be added that shows the output. For the above example, we could do something like the following:

````markdown
<details><summary>Example</summary>
<p>

```go
{
	s := Hello("Bob")
	fmt.Println(s)

}
```

Outputs:

```example
Hello Bob!
```

</p>
</details>
````

# Implementation

It appears that the [doc.Example](https://golang.org/pkg/go/doc/#Example) struct already has a field called `Output` which contains the expected output. I suspect it would be as simple as hooking this up with a new method in `gomarkdoc/lang.Example`, then modifying the `example.gotxt` template to accommodate the new method.

**Comment by princjef** [comment]
Thanks for the thorough analysis @terrabitz! Looking at your PR now

**Comment by princjef** [comment]
This is included in https://github.com/princjef/gomarkdoc/releases/tag/v0.1.2
