### ISSUE TITLE
URLs are escaped and unclickable

### ISSUE THREAD

**Issue by bobheadxi** [princjef/gomarkdoc#29]
URLs included in documentation, e.g.

```go
/*
Package monitoring declares types for Sourcegraph's monitoring generator as well as the generator implementation itself.

To learn more about developing monitoring, see the guide: https://about.sourcegraph.com/handbook/engineering/observability/monitoring

To learn more about the generator, see the top-level program: https://github.com/sourcegraph/sourcegraph/tree/main/monitoring
*/
package monitoring
```

are escaped when rendered, and not clickable:

![image](https://user-images.githubusercontent.com/23356519/100431195-c6b5ca00-30d2-11eb-8a50-17b6095c2803.png)

**Comment by princjef** [comment]
Thanks for reporting @bobheadxi! Let me see if I can work something up to resolve this.

**Comment by princjef** [comment]
This has been fixed in https://github.com/princjef/gomarkdoc/releases/tag/v0.1.3

Let me know if you're still having issues with the latest version.
