### ISSUE TITLE
[Feature request] Make helper functions of `format/base.go` public to be able to easily extend `format.Format`

### ISSUE THREAD

**Issue by bastantoine** [princjef/gomarkdoc#38]
Hello!

I've just discovered your tool, it's awesome and really useful!

I'm using your tool for a work project, but I need to tweak a bit the rendered markdown files. I saw that there are bunch of markdown helpers (`bold`, `header`, `link`...) in [`format/base.go`](https://github.com/princjef/gomarkdoc/blob/master/format/base.go) that you use in all the implementation of [`format.Format`](https://github.com/princjef/gomarkdoc/tree/master/format) (`PlainMarkdown`, `GitHubFlavoredMarkdown` and `AzureDevOpsMarkdown`).

I was wondering if it would be possible to export those helpers so that its easy to create a custom implementation of `format.Format`, without having to rewrite those helpers?

I'd be happy to send a PR if that's okay with you!

**Comment by bastantoine** [comment]
Hello @princjef ! Any news on this?

**Comment by princjef** [comment]
Hey @bastantoine, that sounds like a great idea! If you want to put together a PR with the changes I'll take a look and we can get it merged

**Comment by bastantoine** [comment]
Great, thanks!
