### ISSUE TITLE
formatting issue in case of function signature spanning multiple lines

### ISSUE THREAD

**Issue by pangteypiyush** [princjef/gomarkdoc#46]
There is a little formatting issue in the Index link text for functions which have signature in multiple lines.

This function:
```go
func (vc *ViperConfiguration) Abc(
    name xyz.ProviderName,
    output interface{},
) error
```

has index link text:
```
func (vc *ViperConfiguration) Abc( name xyz.ProviderName, output interface{}, ) error
```

but it should be:
```
func (vc *ViperConfiguration) Abc(name xyz.ProviderName, output interface{}) error
```

**Comment by princjef** [comment]
Thanks for opening an issue! I'm able to reproduce this issue, which appears to be coming from the fact that the multiline signature is being preserved when printing for the index, which is then collapsed by the markdown formatting.

I'll have to see if there's a way for the built in tooling to print the signature in the desired way or if we'll end up needing a custom printer for this (which will get tricky, particularly with inlined types)
