### ISSUE TITLE
Incorrect example naming for struct methods (with suffix)

### ISSUE THREAD

**Issue by thejohnbackes** [princjef/gomarkdoc#47]
I have an example function in my code as follows:

```
func ExampleClient_Update_unset() {
   ...
}
```

`godoc` renders the name as `Example (Unset)`:

![image](https://user-images.githubusercontent.com/13596692/130125446-8e05b2c7-4928-42cd-8d5f-4750e4d92d79.png)

`gomarkdoc` renders the name as `Example`:

```

<details><summary>Example</summary>
<p>

```

![image](https://user-images.githubusercontent.com/13596692/130125648-5b9520f2-8b37-4bad-b6bf-4b1135a9d854.png)

Here is the [relevant documentation](https://pkg.go.dev/testing#hdr-Examples) from the `testing` library:

![image](https://user-images.githubusercontent.com/13596692/130125344-737abbdf-2f28-48f4-837b-35d2761066cb.png)

**Comment by princjef** [comment]
Thanks for reporting this issue! I've found the problem in the code and am working on testing out a fix
