### ISSUE TITLE
GoFlags are not honored for Build Tags

### ISSUE THREAD

**Issue by FloThinksPi** [princjef/gomarkdoc#48]
When i let it run with `GOFLAGS="-tags=psql" gomarkdoc ./... ` and have packages needing this build tag e.g. `// +build psql` the doc is not generated for such files.  GOFLAGS env variable is not honored and i dont see any other way to include such files.

Any Idea ?

**Comment by princjef** [comment]
Good catch. It looks like the processing of the package allows for tags to be specified. Let me see if I can work up a fix

**Comment by FloThinksPi** [comment]
Thanks @princjef 🚀  :)
