### ISSUE TITLE
Command-line install of gomarkdoc no longer compliant post 1.17

### ISSUE THREAD

**Issue by julienbonastre** [princjef/gomarkdoc#49]
Since Go 1.17, one can no longer install packages/modules via the `go get` method as per: https://github.com/princjef/gomarkdoc/blob/master/README.md?L=20

> L20: `GO111MODULE=on go get -u github.com/princjef/gomarkdoc/cmd/gomarkdoc`

**Comment by princjef** [comment]
Thanks for reporting this! Will update with `go install` instructions for golang 1.16+
