### ISSUE TITLE
Add examples to the README

### ISSUE THREAD

**Issue by zimmski** [princjef/gomarkdoc#61]
We are currently looking for a solution that allows us to document our binaries (description of options/arguments, usage, tutorials, ...) + Go packages + packages of other languages + Rest/... APIs.

I stumbled upon this project and the description seems nice. However, i do not see any linked examples for documentation sites that are generated. Could you please add some?

**Comment by shakefu** [comment]
The `README.md` of this repository is generated using the tool. :)

**Comment by princjef** [comment]
This tool does use itself to generate all of the README files in this repository. #73 adds some documentation mentioning that this tool uses itself and where to find the commands it runs.

**Comment by zimmski** [comment]
Great, thanks!
