### ISSUE TITLE
Bug in generating markdown files with ","

### ISSUE THREAD

**Issue by fulviodenza** [princjef/gomarkdoc#68]
Hi! I noticed that when I generate markdown files containing the symbol "," it prints out in the md file this: "'backslash'," (I put the 'backslash' string instead of the symbol because it does not prints the symbol here.

Is there something I'm missing or is it a bug?

To test the issue you can simply create a comment (with one or more lines) like the following:
`// Lorem ipsum dolor sit amet, hello world`

**Comment by fulviodenza** [comment]
Hi @princjef, ping for this issue

**Comment by princjef** [comment]
Thanks for reporting the issue @fulviodenza and @kylie-sre. #70 looks like a valid fix for the issue so we'll focus on getting that in to resolve this.

Out of curiosity, what tool(s) do you use where the escaping is causing you issues? I work and test primarily in GitHub and Azure DevOps, which both have no problem with the escaped characters

**Comment by princjef** [comment]
fixed by #70
