### ISSUE TITLE
Bug in generating markdown files with characters *(){}[]-

### ISSUE THREAD

**Issue by manlopes** [princjef/gomarkdoc#77]
Hi, I've noticed that, when generating markdown files with some characters like "*(){}[]-", the output is not correct and backslashes are added to the md file before each of the characters. See example below:

Source comment:

//  &ast;&ast;param&ast;&ast; c (context.Context): Execution context

markdown output

\\&ast;\\&ast;param\\&ast;\\&ast; ctx \\(context.Context\\): Execution context

This issue is similar to issue https://github.com/princjef/gomarkdoc/issues/68

**Comment by princjef** [comment]
Hi @manlopes, this tool is intentionally aligned with the golang documentation syntax for doc comments, not markdown. This is to maintain consistency with the pkg.go.dev experience and avoid generating documentation that only renders correctly in one place or the other. As a result, markdown-specific syntax like `**` for bold items is intentionally escaped as we don't want things being implicitly interpreted as markdown.

If there are other specific rendering bugs that you've found, please feel free to reactivate this issue. I hope that description helped.
