### ISSUE TITLE
Links in comments aren't generated correctly

### ISSUE THREAD

**Issue by kaiiorg** [princjef/gomarkdoc#83]
Following the formatting guide for [go doc links](https://tip.golang.org/doc/comment#links) results in the angle brackets being escaped and thus links not being rendered correctly. Is there a way to format links to external resources without just pasting the link? I.E., [like this](https://github.com/rs/zerolog), not like this: https://github.com/rs/zerolog

## Example
```go
// GetComponentLogger builds a [ZeroLog] Logger based on provided 'rootLogger' ZeroLog Logger,
// adding 'componentName' and 'levelStr' to log messages.
// Will default to 'Info' Log Level if invalid or no 'levelStr' is provided
//
// [ZeroLog]: https://github.com/rs/zerolog "ZeroLog"
func GetComponentLogger(rootLogger zerolog.Logger, componentName string, levelStr string) zerolog.Logger {
	level, err := zerolog.ParseLevel(levelStr)
	if err != nil {
		level = zerolog.InfoLevel
	}
	return rootLogger.With().Str("component", componentName).Logger().Level(level)
}
```
## Result (raw markdown)
```markdown
GetComponentLogger builds a \[ZeroLog\] Logger based on provided 'rootLogger' ZeroLog Logger, adding 'componentName' and 'levelStr' to log messages. Will default to 'Info' Log Level if invalid or no 'levelStr' is provided

\[ZeroLog\]: https://github.com/rs/zerolog "ZeroLog"

## func [GetHashicorpComponentLogger](<https://github.com/redacted>)

```go
func GetHashicorpComponentLogger(rootLogger zerolog.Logger, componentName string, levelStr string) *logutils.LevelFilter
\```
```

## Result (as rendered by github)
GetComponentLogger builds a \[ZeroLog\] Logger based on provided 'rootLogger' ZeroLog Logger, adding 'componentName' and 'levelStr' to log messages. Will default to 'Info' Log Level if invalid or no 'levelStr' is provided

\[ZeroLog\]: https://github.com/rs/zerolog "ZeroLog"

## func [GetHashicorpComponentLogger](<https://github.com/redacted>)

```go
func GetHashicorpComponentLogger(rootLogger zerolog.Logger, componentName string, levelStr string) *logutils.LevelFilter
```

**Comment by princjef** [comment]
The library did not support go 1.19 features at the time. This is now fixed in the main branch (see this test case example: https://github.com/princjef/gomarkdoc/blob/master/testData/docs/README.md) and will be available in the next release
