### ISSUE TITLE
new headings syntax in go 1.19

### ISSUE THREAD

**Issue by missinglink** [princjef/gomarkdoc#86]
> The # syntax was added in Go 1.19. Before Go 1.19, headings were identified implicitly by single-line paragraphs satisfying certain conditions, most notably the lack of any terminating punctuation.

The current `master` branch doesn't yet support this change, instead writing a literal '#':

<img width="198" alt="Screenshot 2023-02-10 at 14 06 41" src="https://user-images.githubusercontent.com/738069/218099554-7ddf047e-a0a4-4e2c-a058-8bb23d848743.png">

https://go.dev/doc/comment#headings

**Comment by princjef** [comment]
The new headings syntax is now supported via #87 and will be available in the next release
