### ISSUE TITLE
Ignoring appending into generated docs when using -e flag

### ISSUE THREAD

**Issue by codertyler** [princjef/gomarkdoc#91]
I was wondering if we can implemented solution where when when use `-e` flag with a wildcard we don't append new generated docs to an already generated docs?

**Comment by princjef** [comment]
Hi @codertyler, can you elaborate on what you mean by not appending? An example would be helpful to understand the request

**Comment by codertyler** [comment]
We worked out a workaround for this... I think I was using a method incorrectly. Thanks! Closing it.
