### ISSUE TITLE
add support for Template functions

### ISSUE THREAD

**Issue by ccamel** [princjef/gomarkdoc#93]
As far as I can see, it is not possible to define additional Template functions. For example, the following code defines some functions:

```go
		if renderer.tmpl == nil {
			tmpl := template.New(name)
			tmpl.Funcs(map[string]interface{}{
				"add": func(n1, n2 int) int {
					return n1 + n2
				},
 ...
```

but it would be great to be able to add others (such as the functions provided by [Sprig](https://github.com/Masterminds/sprig) for instance), when creating a new renderer (`NewRenderer`).

**Comment by ccamel** [comment]
I can submit a PR if it can help. :relieved:

**Comment by princjef** [comment]
I've put together a small change that adds a `WithTemplateFunc` option to the renderer. Let me know if that solves your issue
