### ISSUE TITLE
Links appear broken in README files

### ISSUE THREAD

**Issue by amayausky** [princjef/gomarkdoc#99]
Noticed this with the v1.0.0 release today. 

It appears links are being parsed into `link[link](link)` which renders incorrectly, for example from the current [README](https://github.com/princjef/gomarkdoc/blob/0124a633aa4a47ce25d0b5f7d70116959e71f42e/README.md?plain=1#L14): `https://pkg.go.dev[https://pkg.go.dev](<https://pkg.go.dev>)`. It looks like that change happened with #89.

Thanks for the great tool!

**Comment by princjef** [comment]
Good catch, thanks for the bug report @amayausky 💯  Luckily an easy fix

**Comment by princjef** [comment]
This is now available in v1.1.0
